function [fitresult, gof] = createFitPhugoid(tout, u, excludedPoints)
%CREATEFIT(TOUT,U)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input: tout
%      Y Output: u
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 21-Apr-2026 09:34:32


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( tout, u );

% Set up fittype and options.
ft = fittype( 'exp(s*x)*(a*cos(d*x)+b*cos(-d*x))+c', 'independent', 'x', 'dependent', 'y' );
% excludedPoints = xData < 0.56;
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = [0 0 0 0.659 -0.039];
opts.Exclude = excludedPoints;

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h = plot( fitresult, xData, yData, excludedPoints );
legend( h, 'Data', 'Excluded Points', sprintf("Fit ($R^2 = %.4f$)",gof.rsquare), 'Location', 'southeast', 'Interpreter', 'latex' );
% Label axes
xlabel( 'Time (s)', 'Interpreter', 'none' );
ylabel( 'u (m/s)' );
grid on
