function [fitresult, gof] = createFitSP(tout, theta)
%CREATEFIT(TOUT,THETA)
%  Create a fit.
%
%  Data for 'untitled fit 2' fit:
%      X Input: tout
%      Y Output: theta
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 21-Apr-2026 10:19:30


%% Fit: 'untitled fit 2'.
[xData, yData] = prepareCurveData( tout, theta );

% Set up fittype and options.
ft = fittype( 'exp(s*x)*(a*cos(d*x)+b*cos(-d*x))+c', 'independent', 'x', 'dependent', 'y' );
excludedPoints = xData < 0.3 | xData>2;
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.Lower = [-Inf -Inf -Inf -10 -5];
opts.StartPoint = [0 0 0 7 -2];
opts.Upper = [Inf Inf Inf 10 0];
opts.Exclude = excludedPoints;

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'untitled fit 2' );
h = plot( fitresult, xData, yData, excludedPoints );
legend( h, 'theta vs. tout', 'Excluded theta vs. tout', 'untitled fit 2', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 'tout', 'Interpreter', 'none' );
ylabel( 'theta', 'Interpreter', 'none' );
grid on;
ylim([-1 0.2]);


